CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
CONFIG_ZMK_USB=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_BACKLIGHT=n

CONFIG_ZMK_SLEEP=n

# Bluetooth
CONFIG_BT_BAS=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# Battery Life Display
# CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

# Dongle
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
