manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import:
        file: app/west.yml
    - name: zmk-dongle-display
      url: https://github.com/englmaxi/zmk-dongle-display
      revision: main
  self:
    path: config
